# Generated by Django 6.0.6 on 2026-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_issue_options_alter_issuecomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='issues/'),
        ),
    ]
